version: "3.7"
services:
    mysql-service:
      image: mysql:8.0.27
      restart: always
      ports:
        - "3306:3306"
      expose: [ 3306 ]
      environment:
        - MYSQL_ROOT_PASSWORD=ThePassword
        - MYSQL_DATABASE=db_example